name: CI Back & Front

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Move in Back
      run: cd Back
      
    - name: Go dossier Back
      run: cd Back/ && ls
      
    - name: Build Docker image
      run: cd Back && docker-compose build && docker-compose up -d && docker-compose exec -T container pwd composer install
      
    - name: Install BDD
      run: cd Back && php bin/console doctrine:migration:migrate && php bin/console doctrine:fixtures:load
      
